name: ai-learning-platform
region: nyc
services:
  # Backend API Service
  - name: backend
    github:
      branch: main
      deploy_on_push: true
      repo: akvimal/learn-aiway
    source_dir: /backend
    dockerfile_path: /backend/Dockerfile
    instance_count: 1
    instance_size_slug: basic-xxs
    http_port: 3000
    routes:
      - path: /api
      - path: /health
    health_check:
      http_path: /health
      initial_delay_seconds: 30
      period_seconds: 10
      timeout_seconds: 5
      success_threshold: 1
      failure_threshold: 3
    envs:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: "3000"
      - key: API_VERSION
        value: v1
      - key: DATABASE_URL
        value: ${ai-learning-db.DATABASE_URL}
      - key: REDIS_URL
        value: ${ai-learning-redis.DATABASE_URL}
      - key: JWT_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_REFRESH_SECRET
        scope: RUN_TIME
        type: SECRET
      - key: JWT_ACCESS_EXPIRATION
        value: 15m
      - key: JWT_REFRESH_EXPIRATION
        value: 7d
      - key: BCRYPT_ROUNDS
        value: "12"
      - key: RATE_LIMIT_WINDOW_MS
        value: "900000"
      - key: RATE_LIMIT_MAX_REQUESTS
        value: "100"
      - key: ALLOWED_ORIGINS
        value: ${_self.PUBLIC_URL}
      - key: LOG_LEVEL
        value: info

  # Frontend Static Site
  - name: frontend
    github:
      branch: main
      deploy_on_push: true
      repo: akvimal/learn-aiway
    source_dir: /frontend
    build_command: npm run build
    output_dir: /dist
    instance_count: 1
    instance_size_slug: basic-xxs
    routes:
      - path: /
    static_sites:
      - catchall_document: index.html
    envs:
      - key: VITE_API_BASE_URL
        value: ${backend.PUBLIC_URL}/api/v1

# Database - PostgreSQL
databases:
  - name: ai-learning-db
    engine: PG
    version: "16"
    production: true
    cluster_name: ai-learning-db-cluster
    db_name: ai_learning
    db_user: ai_learning_user
    size: db-s-1vcpu-1gb
    num_nodes: 1

  # Redis Cache
  - name: ai-learning-redis
    engine: REDIS
    version: "7"
    production: true
    cluster_name: ai-learning-redis-cluster
    size: db-s-1vcpu-1gb
    num_nodes: 1

# Domains (optional - add your custom domain)
# domains:
#   - domain: yourdomain.com
#     type: PRIMARY
#     zone: yourdomain.com
#   - domain: www.yourdomain.com
#     type: ALIAS
#     zone: yourdomain.com

# Alerts (optional)
alerts:
  - rule: DEPLOYMENT_FAILED
  - rule: DOMAIN_FAILED

# Ingress (traffic routing)
ingress:
  rules:
    - component:
        name: backend
      match:
        path:
          prefix: /api
    - component:
        name: backend
      match:
        path:
          prefix: /health
    - component:
        name: frontend
      match:
        path:
          prefix: /
